version: '3.3'

services:
    #######################################
    # Node.js
    #######################################
    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=8.9.4
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=development
        volumes:
            - ../:/opt/app
        entrypoint: run-nodock "yarn dev"
        tty: true
        ports:
            - "56745:56745"
        links:
            - mongo
    #######################################
    # MySQL
    #######################################
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"
    #######################################
    # Mongo
    #######################################
    mongo:
        build: ./mongo
        expose:
            - "27017"
        volumes:
            - ./data/mongo/:/var/lib/mongodb
    #######################################
    # Redis
    #######################################
    redis:
        build: ./redis/
        volumes:
            - ./data/redis/:/data
    #######################################
    # Nginx
    #######################################
    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true
        links:
            - node
    #######################################
    # CertBot
    #######################################
    certbot:
        build:
            context: ./certbot
        links:
            - nginx
        volumes:
          - ./certbot/letsencrypt/:/var/www/letsencrypt
          - ./certbot/certs/:/var/certs
    #######################################
    # RabbitMQ
    #######################################
    rabbitmq:
        build:
            context: ./rabbitmq
            args:
                - MANAGEMENT=false
                - FEDERATION=false
                - RABBITMQ_DEFAULT_USER=guest
                - RABBITMQ_DEFAULT_PASS=guest
        expose:
            - "5672"
    #######################################
    # WorkSpace
    #######################################
    workspace:
        build:
            context: ./workspace
            args:
                - NODE_VERSION=latest
                - TZ=UTC
        links:
            - nginx
        volumes:
            - ../:/opt/app
